### ISSUE TITLE
Sample Output

### ISSUE THREAD

**Issue by bkj** [mfaruqui/crosslingual-cca#3]
Is it possible to include example intermediate results / final results?  I'm interested in re-implementing the `project_vectors.m` in python, but I don't have MATLAB so it'd be hard to validate my implementation.

**Comment by yuchenlin** [comment]
Hi, do you have some update? I also wanna re-implement this in python.

**Comment by wammar** [comment]
Hello! Both Manaal and I stopped working on this for quite sometime and moved on to work on other things.
